### ISSUE TITLE
R4.0.6 Checker Packages

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1169]
Link to [Squad 1 R4.0.4 MVP mural](https://app.mural.co/invitation/mural/ibmaccessibility7766/1654188680920?sender=mhoov&key=920e0caa-f7b8-46eb-8340-12f13dcb2c13)
Refer to issue #5135 for summary

Link to [Squad 2 R4.0.5 w/ Checker Packages Activities](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1661372689561/4f204696258e3664a65f48a1fc1e6fed5a1e955b?sender=johlic)

Webex meeting recording: Checker packages overview by Tom
Password: wPW2eXre
[Recording link](https://ibm.webex.com/ibm/ldr.php?RCID=9b264fd62bcd4a74636efda432565dfb)

[7/21 slack thread](https://ibm-studios.slack.com/archives/GSGN6RQA2/p16583466870664690) - notes from Tom's demo

It would be good if we can get a video or two out of the demo that can be reused on /able and/or for users in this research.

Potential questions:
- Do users want/prefer/need to have Checker in Storybook over CI plugins (or in addition to)
- What other tools do you use and what do they do that ours do not
- Comparative questions: setup, runtime, output differences
- baseline function -is it sufficient or need changes
- What is your general process? pain points?
- Adoption pain points - how easy was it to pick up and use
- If it doesn't come out: "What are some things you wish the tool would/could do"
- What is your testing framework environment? (Travis, node, karma, cypress, selenium, playwrite, etc)
- User guides: Can they locate? Are they helpful?
- Do you know you are supposed to look at potential violations
- if you are current user - do you review potential violations?

## Epic Details
- **User Story**: The additional features most desired by DevOps developers are identified for implementation in the next release 
- **Playback Demonstration**: A summary of the research results will cover the users and methods employed, an assessment of the data collected including identification of the key pain points, features or changes identified, any insight about the user base (i.e., do they review PVs) and a proposal for a Checker Packages update. 
- **Metric**: Reaction from research participants; results of survey on slack to confirm priorities; time on task? (future)
- **Comms**: survey on slack (identify channels) to confirm priorities; release announcement (future)

## What project/section is the Epic for?

- [ ] `able site - Toolkit`
- [x] `a11y Checker - Assessment`
- [ ] `a11y Checker`
- [ ] `checklist`
- [ ] `ACS`
- [ ] `other`

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] ~All code committed to main branch~
- [ ] ~All unit tests pass (including accessibility)~
- [ ] ~Demo works in staging environment~
- [ ] At least one performance metric / monitor constructed

**Comment by sct-will** [comment]
Related issues:
- [ ] https://github.com/IBMa/equal-access/issues/955
- [ ] https://github.com/IBMa/equal-access/issues/425

**Comment by MHoov** [comment]
@sct-will did you ever create an issue to address the boilerplate recommendation?
