### ISSUE TITLE
R5.3 Checker Extension work

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1516]
R5.3 Mural  https://app.mural.co/invitation/mural/ibmaccessibility7766/1686667350232?sender=mhoov&key=60f7a5c3-d312-4828-be4e-c50e2c37e1cb

## Epic Details
- **User Story**: Product teams will have new features that improve the identification of accessibility issues and remediation steps as part of their automated testing.

1. User needs to be aware that there are two views to the checker (checker view and assessment view) and what the views offer and how to access them so that they can effectively know which view is better for their tasks.
2. User needs to be able to show that a Needs review issue has be reviewed and should not show up in the issues list anymore.
3. User needs to be notified if they try to change the rule set while they have stored scans so that they can cancel the rule set change and keep their stored scans or change the rule set and lose any stored scans.

- **Playback Demonstration**: _what will you be able to show at the end of the release / point release to demonstrate how you accomplished your user story. If possible, list what you target to demonstrate for each sprint_ 
- **Metric**: _how can we measure the impact of this change_
- **Comms**: _when completed who should you communicate this change to, what will you tell them (concisely), and where?_

## What project/section is the Epic for?

- [ ] `able site - Toolkit`
- [ ] `a11y Checker - Assessment`
- [x] `a11y Checker`
- [ ] `checklist`
- [ ] `ACS`
- [ ] `other`

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed
