### ISSUE TITLE
R5.3 Packages

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1517]
R5.3 Mural https://app.mural.co/invitation/mural/ibmaccessibility7766/1686667350232?sender=mhoov&key=60f7a5c3-d312-4828-be4e-c50e2c37e1cb

## Epic Details
- **User Story**: Product teams using webdriver.io or JUnit will be able to integrate automated accessibility testing into their test environments.
- **Playback Demonstration**: Will be able to show automated accessibility checking running as part of Java/JUnit and webdriver.io environments. 
- **Metric**: We will be able to show usage in the tool metrics in these environments
- **Comms**: Advertise on the #accessibility-at-ibm channel and Accessibility updates
  - webdriver.io

## What project/section is the Epic for?

- [ ] `able site - Toolkit`
- [ ] `a11y Checker - Assessment`
- [ ] `a11y Checker`
- [ ] `checklist`
- [ ] `ACS`
- [x] 'Packages'
- [ ] `other`

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed
