### ISSUE TITLE
R5.3 Rules

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1523]
R5.3 Mural https://app.mural.co/invitation/mural/ibmaccessibility7766/1686667350232?sender=mhoov&key=60f7a5c3-d312-4828-be4e-c50e2c37e1cb

## Epic Details
- **User Story**: _the user (both developer & auditor) – will continue to be wow'd seeing new rules and improved (fixed) existing rules that identify fewer false positives, improved cover of accessibility and web technology specifications, and user-reported findings_
- **Playback Demonstration**: _what will you be able to show at the end of the release to demonstrate how you accomplished your user story. 
  - See [Roadmap](https://github.com/IBMa/equal-access#workspaces/equal-access-61ae71f9f8b4ec001e136462/roadmap) of Epic and showcase playbacks
- **Metric**: _how can we measure the impact of this change?_
  - new & fixed rules
  - fixes to Engine
  - updates to Help and messages 
  - See the tracking table in [box](https://ibm.ent.box.com/notes/1116814404939)
- **Comms**: _when completed who should you communicate this change to, what will you tell them (concisely), and where?_
  - [Release Notes](https://github.com/IBMa/equal-access/releases/) and post to SLack channel

## What project/section is the Epic for?

- [x] `a11y Checker - Assessment`
- [x] `a11y Checker - Developer`

## Definition of Done

- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All unit tests pass (including accessibility)
- [x] All code committed to master
~~- [ ] Demo works in staging environment~~
~~- [ ] At least one performance metric / monitor constructed~~
