### ISSUE TITLE
R5.4 Rules help

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1655]
Refer to mural R5.4 _add link_

## Epic Details
- **User Story**: _what does the user need – include some sort of WOW element_
  - User has improved Help guidance, reducing the need to be a SME
- **Playback Demonstration**: _What will you be able to show at the end of the release/point release to demonstrate how you accomplished your user story? If possible, list what you target to demonstrate for each sprint_ 
  - Team and squad reviews during Showcases
- **Metric**: _How can we measure the impact of this change_
  - The # of Help files improved (of the 172 current Help files) 
- **Comms**: _When completed who should you communicate this change to, what will you tell them (concisely), and where?_
  - **Release Notes** will highlight **_What's Changed_** 

## What project/section is the Epic for?

- [engine](https://github.com/IBMa/equal-access/issues#workspaces/equal-access-61ae71f9f8b4ec001e136462/board?labels=engine&releases=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTQ1MzM)

## Definition of Done

- [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to the main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in the staging environment
- [ ] At least one performance metric / monitor constructed
