### ISSUE TITLE
R6.1 Rules

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1810]
## Epic Details
- **Hill**: Users will have an improved experience with the checker or tools because the engine rules will be more specific and easier to understand, and more compliant with community test cases (ACT). Overall, IBM will have better and more compliant accessibility tools.   
- **Playback Demonstration**: Each sprint replay will use [replay template](https://ibm.ent.box.com/file/1331599657851) to explain the issue, including user impact, supporting standard(s), what's broken, fix, and test case(s) to show the issue and the fix.
- **Metric**: The issue will be fixed based on the [defined priority](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1705693042364/47a298488ca8565620c7068677ae3c40b6666dbc?sender=shunguoy7634). The [Engine rules 2024 ](https://ibm.ent.box.com/notes/1116814404939)is updated after each new rule or fix. The end of the release will have [Release outcome](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1705693042364/47a298488ca8565620c7068677ae3c40b6666dbc?sender=shunguoy7634), including the number of rules created or updated and the number of issues or false positives/negatives fixed.
- **Comms**: The overall release notes, update calls, other developer meetings, etc. will contain the engine changes that will be an integral part of the checker and tools.

## What project/section is the Epic for?

- [toolkit](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=toolkit)
- [acs](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=acs)
- [a11y central](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=a11y%20central)
- [acr](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=acr)
- [requirements](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=requirements)
- [special airplane](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=special%20airplane)
- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)
- [carbon](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=carbon)
- [standards](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=stds)
- other

## Definition of Done

- [x] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All code committed to main branch
- [x] All unit tests pass (including accessibility)
- [x] Demo works in staging environment
- [x] At least one performance metric / monitor constructed
- [x] The [Engine rules 2024 ](https://ibm.ent.box.com/notes/1116814404939) is updated.
