### ISSUE TITLE
R6.3 Legacy code cleanup

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1970]
The engine code has lots of legacy code with duplicated or similar functions that caused maintenance issues. We might need to change multiple places with a spec change or a fix to an issue, this is costly. 

## Epic Details
- **Hill**: Users will have an improved experience with the checker or tools because the code of engine rules will be cleaner, run faster, and be more compliant with the latest specs. Overall, IBM will have better and more compliant accessibility tools.
- **Playback Demonstration**: Each sprint replay will use [replay template](https://ibm.ent.box.com/file/1331599657851) to explain the issue, including user impact, supporting standard(s), what's broken, fix, and test case(s) to show the issue and the fix. 
- **Metric**: # of code functions are merged and fixed. The [Engine rules 2024 ](https://ibm.ent.box.com/notes/1116814404939)is updated after each new rule or fix. The end of the release will have [Release outcome](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1705693042364/47a298488ca8565620c7068677ae3c40b6666dbc?sender=shunguoy7634), including the number of rules created or updated and the number of issues or false positives/negatives fixed.

  What was updated in this release? Over 100 rules were updated for the following major changes:
        Merge DomWalker and NodeWalker
        Merge isNodeVisible(), isNodeDisabled
        Update aria definitions
        Change the multiple-role resolving
        Split RTPUtil into VisUtil, CSSUtil, AriaUtil, ColorUtil, TableUtil, CommonUtil
        Update the code style into ts classes
        Rewrote accessible name calculation for all the elements, and replaced the original implementation with the new calculation in many rules
        Add a lot more caching for performance

    After the engine update, the overall performance was improved with an average time reduced to 43 to 66% of the original time.

- **Comms**: The overall release notes, update calls, other developer meetings, etc. will contain the engine changes that are an integral part of the checker and tools.
     The update was released in Checker 3.1.77 (browsers and NPM stores).

- **Lessons learned**: All the items are released in the same package and release. The advantage is that it saves time from dependencies and potential conflicts of otherwise smaller releases due to the review, test, and merge period, and the disadvantage is that customers have to wait until the end to use the new changes.

- [x] #1977 
- [x] #1974 
- [x] #1971 
- [x] #1973 

## What project/section is the Epic for?

- [toolkit](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=toolkit)
- [requirements](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=requirements)
- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)
- [standards](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=stds)
- other

## Definition of Done

- [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All code committed to main branch
- [x] All unit tests pass (including accessibility)
- [x] Demo works in staging environment
- [x] At least one performance metric / monitor constructed

**Comment by MHoov** [comment]
Notes from Aug 9 call:
- Not possible to do it all during this release
- Tom suggests carving out a chunk
- Primary goal is cleaning out the code, not necessarily performance improvements
- Tom looked at javadoc, trying to get a sense for what the problem is
- Shunguo will start his exploration after his vacation
