### ISSUE TITLE
Engine performance improvement

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1975]
analyze the rule engine to improve performance.
also from Tom: Some good pages for performance analysis. I think these are large enough that we'll have trouble with them no matter what, but, would be good if we can find some optimizations. For instance, we may need to be smarter with our contrast calculations - find some way to carry some of the expensive calculations between nodes (though not sure how we'd do that offhand).

- [ ] #1976 

https://ibm-studios.slack.com/archives/C036P1CTN/p1723020298582739

## Epic Details
- **Hill**: _what does the user need – include some sort of WOW element_
- **Playback Demonstration**: _what will you be able to show at the end of the release / point release to demonstrate how you accomplished your user story. If possible, list what you target to demonstrate for each sprint_ 
- **Metric**: _how can we measure the impact of this change_
- **Comms**: _when completed who should you communicate this change to, what will you tell them (concisely), and where?_

## What project/section is the Epic for?

- [toolkit](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=toolkit)
- [acs](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=acs)
- [a11y central](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=a11y%20central)
- [acr](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=acr)
- [requirements](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=requirements)
- [special airplane](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=special%20airplane)
- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)
- [carbon](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=carbon)
- [standards](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=stds)
- other

## Definition of Done

- [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed

**Comment by MHoov** [comment]
Will create a new Epic at the appropriate time
