### ISSUE TITLE
R6.3 Java accessibility-checker

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1985]
### Hill

Development teams will be able to use the accessibility-checker from the Java environment

Initial release will just support JSON and CSV reports

### Playback Demonstration

Will demonstrate boilerplates using java

### Metric

Scans for `java-accessibility-checker`

### Comms

Notify via IBM Slack and reach out to teams who have asked for Java checking

### Project

other

- [x] #398 
- [x] #1982 
- [x] #1988 
- [x] #1992 
- [x] #1993 
- [x] #1994 
- [x] #1995 
- [x] #1997
- [x] #1999

## Definition of Done

- [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All code committed to main branch
- [x] All unit tests pass (including accessibility)
- [x] Demo works in staging environment
- [x] At least one performance metric / monitor constructed

**Epic results**
Did you accomplish your Hill? Yes
If not, what is remaining? N/A
Will your final playback match what is recorded for Playback Demonstration? Yes
Collect your metrics: 1983 scans as of 11/12/2024
Comm's: Completed
Lessons Learned about this activity or Release: How to publish a java package

**Comment by tombrunet** [comment]
* Code complete. 
* Automated tests successful
* Automated build tested (but not as a full release)
* Javadoc reviewed
* Metrics added to regular tool usage
