### ISSUE TITLE
R6.3 Rules

### ISSUE THREAD

**Issue by philljenkins** [IBMa/equal-access#1998]
The Checker has some remaining issues in the backlog that need to be resolved as efficiently as possible. See [Bug](https://github.com/IBMa/equal-access/issues/1986) Epic for new issue that came in from our users after the start of this release cycle..

## Epic Details

- **Hill**: 
Users will have an improved experience with the Checker because the engine rules will be more specific and easier to understand, and more compliant with community test cases (ACT). Overall, IBM will have better and more compliant accessibility tools to help teams make products and apps accessible (compliant with standards).

- **Playback Demonstration**: Each sprint replay will use [rules showcase template](https://ibm.box.com/s/idg9kyep9gw3gshecifx92smefum3fjh) to explain the issue, including user impact, supporting standard(s), what's broken, fix, help, mapping, and test case(s) to show the issue and the fix.    

- **Metric**: # of rules and help files that are fixed and merged. The [Engine rules change summary2024 ](https://ibm.ent.box.com/notes/1116814404939) is updated after each new or fixed rule, help, or Engine change. 
   - ~~The end of the release will have [Release outcome on Mural](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1722876516020/b39985f91eef42f9add304c72b7896bfecd159e0?sender=pjenkins8040), including the number of rules created or updated and the number of issues or false positives/negatives fixed~~.
   - Each Checker version deployed to the stores also includes the [Release Notes](https://github.com/IBMa/equal-access/releases) that includes the list of fixes and features that users read.

**Issues fixed: 13**
**Help files updated: 5**
**New issues triaged: 25**
**Versions released: 3  (v3.1.75, v3.1.76, v3.1.37) to the stores**
   
- **Comms**: The team's overall release notes posted to Slack, Office Hours, other developer meetings, etc. will contain the engine changes, especially the new [Checker Rule Set deployment dates](https://www.ibm.com/able/requirements/checker-rule-sets) that will be an integral part of the communications, such as the Rule Set Options in the Checker Settings. 
- Note: Improvements to the UI and new features are **_not_** part of this Rules/Engine Epic, but are part of the Comms..

1.   #1938 
1.   #1958 
1.   #2013 
1.   #2004 
1.  #1973 
1.  #1972 
1.  #1971 
1.  #1974 
1.  #1977 
1.  #2003 
1.  #2029 
1.  #2058 
1.  #2037 
1.  #2052 
1.  #2057 
1.  #2060
1.  #2068 
1.  #2055 
1.  #2070 
1.  #2028 
1.  #2030 
1.  #2065 

## What project/section is the Epic for?

- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)
- [ACT](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/) Checker implementation report

## Definition of Done

- [ ] ~~Results are added to the Release Mural with a description of what was accomplished, KPIs, etc.~~
- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All code committed to main branch
- [x] All unit tests pass (including accessibility)
- [x] Demo works in staging environment
- [x] At least one performance metric / monitor constructed

### Lessons learned and observations
- Some issues require investigation with multiple browsers, such as Firefox vs Chrome, JAWS screen reader, and Carbon implementations.

**Comment by philljenkins** [comment]
Start reviewing this Epic. At the end of sprint 12 we should have the following documented in this Epic to share at the final Showcase:
## Epic details
- [ ] Did you accomplish your Hill? If not, what is remaining?
- [ ] Will your final playback match what is recorded for Playback Demonstration?
- [ ] Collect your metrics
- [ ] Comm's
### Definition of Done
- [ ] Indicate what has been completed
- [ ] Identify what needs to happen in the final sprint
- [ ] Lessons Learned about this activity or Release
