### ISSUE TITLE
Deployment of 4.x release

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#2010]
General tasks
* [ ] Code clean up - Remove all the generated code (e.g. src folder) from the repositories
* [ ] Pre-test the latest Node.js (v21) in development environment to see the impact and issues that might be related to the Node versions.
* [ ] Generate all the JMS imports with extension (.js) required by JMS
    For example,
          from: import { IConfigInternal } from "./common/config/IConfig"
          To: import { IConfigInternal } from "./common/config/IConfig.js"
 
  This is to remove the currently used “experimental-specifier-resolution=node” option, which might be removed future by JMS.
 
* [ ] Create both CJS and MJS for the packages of the engine, karma, cypress etc. The current engine code is in ts, but the karma and cypress code seem in js, and might need to convert to the ts first
* [ ] Automated tests to include both CJS and JMS, which also tests the cis and mis versions of the engine.  
* [ ] Test as a user (install rpm, write custom code) for both cis and mis of the packages. 
* [ ] Do we need to provide the boilerplates for both cis and mis?
