### ISSUE TITLE
R6.x HTML Reports

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#2019]
## Epic Details
- **Hill**: Update the HTML report in the checker and packages to match extension's UI and content to make it easier for the user to flip back and forth between the extensions real time report and the saved HTML report without losing context.
- **Playback Demonstration**: Demonstrate the new HTML report with the new UI and content.
- **Metric**: Feedback from users.
- **Comms**: In the checker release notes.

## What project/section is the Epic for?
- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)

## Related Issues to this Epic:
Please mark as done once the ticket is done and have pass QA testing 

- [x] #2024
- [x] #2026
- [x] #2035 
- [x] #2048 

all in final PR

## Definition of Done

- [x] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All code committed to main branch
- [x] All unit tests pass (including accessibility)
- [x] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed

**Comment by tombrunet** [comment]
Basically how the report is built and used by tools:
* The as-is code is in the `report-react` project and built with `npm run build`.
* When the build is run, the `report-react/build/genReport.js` and `genReport.tsx` files are created, which contain a function that takes a report as input and creates a stand-alone HTML file for the report as a string (which can then be written as a file)
* You can find how this function is called and the format of the report here: https://github.com/IBMa/equal-access/blob/master/common/module/src/report/ACReporterHTML.ts#L28

How the genReport function is created:
* The skeleton HTML files is at https://github.com/IBMa/equal-access/blob/master/report-react/public/index.html . You'll see `ACEREPORT = {};` where the HTML report is injected into the file
* The root react file is https://github.com/IBMa/equal-access/blob/master/report-react/src/index.tsx
* https://github.com/IBMa/equal-access/blob/master/report-react/gulpfile.js takes the built .css and .js files and pushes them into the skeleton HTML file for a single stand-alone file.

Some basic problems with the current solution:
* The current built file is ~1MB (even for an almost empty report), which adds a lot of overhead to the reports
* The report design has not been kept up-to-date with the extension design (see below)

As-is design:

![Image](https://github.com/user-attachments/assets/3abe34fb-0c91-44fa-8a50-15d4bf76e5cb)

vs extension report designs:

![Image](https://github.com/user-attachments/assets/0cf54ce2-101f-4463-9f3e-9989ee4e7af7)

![Image](https://github.com/user-attachments/assets/32e8fc63-6d7d-4413-88e4-318dd7febba2)

Note: The checkboxes on the reports won't be needed.

Ideally, we can pull in the same code for both the extension and the report and keep them in sync (minus the checkbox behaviors). We can talk more about design specifics, but this is a general idea of the work needed.

**Comment by MHoov** [comment]
Notes from 29 August meeting:
- Tom said not to worry about the file size yet - get started with the design.
- Josiah suggested starting with the cards.

See recording in Teams for additional details.

**Comment by philljenkins** [comment]
Start reviewing this Epic. At the end of sprint 12 we should have the following documented in this Epic to share at the final Showcase:
## Epic details
- [ ] Did you accomplish your Hill? If not, what is remaining?
- [ ] Will your final playback match what is recorded for Playback Demonstration?
- [ ] Collect your metrics
- [ ] Comm's
### Definition of Done
- [ ] Indicate what has been completed
- [ ] Identify what needs to happen in the final sprint
- [ ] Lessons Learned about this activity or Release
