### ISSUE TITLE
Epic: ACT Inconsistency Issues

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#2099]
The Checker has some remaining inconsistency issues with the ACT test suit.  This Epic is to resolve those issues and any potential new issues during the release cycle.

#### Hill 
Users want the Checker to align with industry-standard ([ACT](https://act-rules.github.io/pages/about/)) and to have fewer bugs and false positives

#### Playback Demonstration
- Each sprint replay will use [rules showcase template](https://ibm.box.com/s/idg9kyep9gw3gshecifx92smefum3fjh) to explain the issue, including user impact, supporting standard(s), what's broken, fix, help, mapping, and test case(s) to show the issue and the fix.    
-   Review ACT's mapping (rules to Success Criteria (checkpoints) against Checker's and see if Checker has conflicts - where Checker disagrees, and decide if Checker wants to do anything about it. Review recommendations with Subject Matter Experts (SME Connection)
- W3C ACT published and proposed rule - gaps
   - [ACT rule status sheet](https://docs.google.com/spreadsheets/d/1OSkPFocXk4K3zYLnwS78WLsWO4PvE5yRcsauyefuIUI/edit?pli=1#gid=0)
   - Take discrepancies to W3C's SME Connection to decide what needs to have a Git issue

#### Metrics
- Number of rules and help files that are fixed and merged. The [Engine rules change summary2024 ](https://ibm.ent.box.com/notes/1116814404939) is updated after each new or fixed rule, help, or Engine change. 
- Each Checker version deployed to the stores also includes the [Release Notes](https://github.com/IBMa/equal-access/releases) that include the list of fixes and features that users read.
- Improvement displayed in [Checker's ACT implementation report](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/) 
   - **Before** (as of 7 November 2024)
   - ![Image](https://github.com/user-attachments/assets/fa9cf388-60a5-4d00-93d8-70f7a4846267)
   - **After**
   - 
   
#### Comms
The team's overall release notes posted to Slack, Office Hours, other developer meetings, etc. will contain the engine changes, especially the new [Checker Rule Set deployment dates](https://www.ibm.com/able/requirements/checker-rule-sets) that will be an integral part of the communications, such as the Rule Set Options in the Checker Settings. 

### Issues assigned/related to this Epic:
1. #2089
2. #2090 
3. #2091 
4. #2092

#### Related issues
6. Closed original #2030 
7. Opened issue against ACT: [Scrollable content [0ssw9k]: Equal Access checker listed as inconsistent because it doesn't report additional AAA criteria #2198](https://github.com/act-rules/act-rules.github.io/issues/2198) 
## What project/section is the Epic for?

- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)
- [ACT](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/) Checker implementation report

## Definition of Done

- [x] All content has been reviewed for grammar, spelling, style and technical accuracy
- [x] All code committed to main branch
- [x] All unit tests pass (including accessibility)
- [x] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed

### Lessons learned and observations
ACT test cases will keep changing as new rules are created and existing rules, including test cases, are updated.

**Comment by MHoov** [comment]
Closing 
- #2095 

Release start: [Showcase Epic ACT consistency 2024-11-19](https://ibm.box.com/s/0o14rwpxyyiqsgh5de7gptbzdheu1k0h)
Release end: [Showcase Epic ACT consistency 2025-02-05](https://ibm.box.com/s/lbm1l2svfyd73b97ltx1novb30ezk8l0)
