### ISSUE TITLE
Epic: Bugs - High Priority Tool & Rule Issues from Backlog & Triages

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#2100]
The Checker has some remaining high-priority issues in the backlog and from in-release triages that need to be resolved in a timely manner. This Epic is for the issues remaining in the backlog and new issues that come from our users during this release cycle and are determined with priority during the triages.

### Hill 
Users will have an improved experience with the Checker because the engine rules will be more specific, easier to understand, and more compliant with community test cases (ACT). Overall, IBM will have better and more compliant accessibility tools to help teams make products and apps accessible (compliant with standards).

### Playback Demonstration
- Each sprint replay will use [rules showcase template](https://ibm.box.com/s/idg9kyep9gw3gshecifx92smefum3fjh) to explain the issue, including user impact, supporting standard(s), what's broken, fix, help, mapping, and test case(s) to show the issue and the fix.    

### Metrics
- Number of rules and help files that are fixed and merged. The [Engine rules change summary2024 ](https://ibm.ent.box.com/notes/1116814404939) is updated after each new or fixed rule, help, or Engine change. 
- Each Checker version deployed to the stores also includes the [Release Notes](https://github.com/IBMa/equal-access/releases) that include the list of fixes and features that users read.
   
### Comms
- The team's overall release notes posted to Slack, Office Hours, other developer meetings, etc. will contain the engine changes, especially the new [Checker Rule Set deployment dates](https://www.ibm.com/able/requirements/checker-rule-sets) that will be an integral part of the communications, such as the Rule Set Options in the Checker Settings. 

### Issues assigned to this Epic:
1. #2081 
2. #2087 
3. #2088 

### Other related Issues possible for this release
1. #2080 
2. #2082 
3. #2085 
4. #2103 

## What project/section is the Epic for?

- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)
- [ACT](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/) Checker implementation report

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment

### Lessons learned and observations
It's only partially done.  The reason is the high-priority issues from the triages take more priority.; (2) v3 and v4 parallel deployment for customer's needs;

**Comment by MHoov** [comment]
Closing - incomplete issues are being moved to Tools Backlog board and will reviewed during backlog grooming for future releases

- #2122 
- #2123 
- #2135 
- #1578 
- #2120 
- #2124 
- #2054 
- #2134 
- #2141 
- #2146 
- #2157 
- #2176
