### ISSUE TITLE
R4.0.1 Fix/Update Engine Rules

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#591]
Checker squad process:  https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1638803758658/c42ba39b1bab6a738096971da653249fe0d813da?sender=johlic

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/ce31869f-d4ed-4a6c-a0a6-ec4487ac8edb)

## Epic Details
- **User Story**: 
![image](https://media.github.ibm.com/user/169438/files/67645d80-d5c0-11eb-893b-837d3c229c0e)

- **Playback Demonstration**: 
1. Demonstrate a select set of rules to show the improvements
2. Demonstrate any update to the help
3. Explain how the rule improvement helps the user.
- **Metric**: count of rules corrected, added or improved; monitor user reporting of false positive or false negatives
- **Comms**: Should be announced at release the time of the rule(s)

## Definition of Done
- [ ] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule developed (Dev)
- [ ] message written (SME)
- [ ] help written (SME)
- [ ] All code committed to main branch (Dev / SME)
- [ ] All unit tests pass (including accessibility) (Dev / Test)
- [ ] Rule(s) works in staging environment (Dev / Test)
