### ISSUE TITLE
[Bug]: deprecated elements, attributes, and aria-attributes

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#677]
### Project

a11y checker engine

### Description

This is to enhance the "RPT_Elem_Deprecated" rule:
  
- [x] need to be added to the ruleset
- [x] need to add a help file
- [x] rule messages need to be more specific with the element or attribute name(s)
- [x] need to add deprecated aria-attributes (aria 1.2) to the list 
- [x] rule implementation
- [x] rule test cases
