### ISSUE TITLE
R4.0.3 - Checker extension issues

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#755]
## Epic Details
- **User Story**: _what does the user need – include some sort of WOW element_
- **Playback Demonstration**: _what will you be able to show at the end of the release / point release to demonstrate how you accomplished your user story. If possible, list what you target to demonstrate for each sprint_ 
- **Metric**: _how can we measure the impact of this change_
- **Comms**: _when completed who should you communicate this change to, what will you tell them (concisely), and where?_

## What project/section is the Epic for?

- [ ] `able site - Toolkit`
- [ ] `a11y Checker - Assessment`
- [x] `a11y Checker`
- [ ] `checklist`
- [ ] `ACS`
- [ ] `other`

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed

### Describe what needs to be accomplished
Epic for tracking both accessibility and implementation bugs within the Accessibility Checker extension(s) during Release 4.0.3

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/d80866d3-7289-4de1-9354-7b39c8a83d08)

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/4886720c-3863-46eb-9aa2-ce986b6bdd33)
