### ISSUE TITLE
[Help - new rule - TS1] element_tabbable_off_screen [Interactive element off the page]

### ISSUE THREAD

**Issue by philljenkins** [IBMa/equal-access#873]
### Tasks
* [x] develop Help and messages per new rule discussions and style guidelines
* [x] review with dev and rule logic
* [x] peer review with other SMEs 
* [x] implement in branch 
* [x] unit test local

### Why does this need to be accomplished
_Reduce manual effort to preform keyboard "tabstop" testing and improve Help_

### Related issues or references
_New rule_

**Comment by philljenkins** [comment]
New rule discussion in Box
[[new] element_tabbable_off_screen](https://ibm.ent.box.com/notes/951753834596)
includes draft Help and messages

**Comment by philljenkins** [comment]
* [ ] peer review completed w Shari
* [ ] edits completed
* [ ] peer review w Mike
* [ ] edits completed

**Comment by philljenkins** [comment]
pushed the help including example code to the branch dev-851
[element_tabbable_off_screen.html](https://github.com/IBMa/equal-access/blob/dev-851/accessibility-checker-engine/help-v4/en-US/element_tabbable_off_screen.html)

**Comment by eirckr** [comment]
Using local server the rule is not triggering.
