### ISSUE TITLE
R4.0.4 Checker extension issues

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#979]
[Link to Squad 2 R4.0.4 MVP Mural](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1654190052950/48be25d2c5c39a4f258f0e4e454c2207c5a8b9eb?sender=johlic)

## Epic Details
- **User Story**: Users need to be assured that bugs and issues are being addressed appropriately
- **Playback Demonstration**: Checker updates and fixes will be demonstrated at the end of the Release 
- **Metric**: _how can we measure the impact of this change_
- **Comms**: Updates and fixes will be addressed in Release notes in this GitHub repo

## What project/section is the Epic for?

- [ ] `able site - Toolkit`
- [ ] `a11y Checker - Assessment`
- [x] `a11y Checker`
- [ ] `checklist`
- [ ] `ACS`
- [ ] `other`

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed
