### ISSUE TITLE
R4.0.4 Fix/Update Engine Rules

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#980]
[Link to Squad 2 R4.0.4 MVP Mural](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1654190052950/48be25d2c5c39a4f258f0e4e454c2207c5a8b9eb?sender=johlic)

## Epic Details
- **User Story**: _what does the user need – include some sort of WOW element_
- **Playback Demonstration**: _what will you be able to show at the end of the release / point release to demonstrate how you accomplished your user story. If possible, list what you target to demonstrate for each sprint_ 
- **Metric**: _how can we measure the impact of this change_
- **Comms**: _when completed who should you communicate this change to, what will you tell them (concisely), and where?_

## What project/section is the Epic for?

- [ ] `able site - Toolkit`
- [ ] `a11y Checker - Assessment`
- [ ] `a11y Checker`
- [ ] `checklist`
- [ ] `ACS`
- [ ] `other`

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed
