### ISSUE TITLE
R4.0.4 ACT Mapping

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#981]
[Link to Squad 2 R4.0.4 MVP Mural](https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1654190052950/48be25d2c5c39a4f258f0e4e454c2207c5a8b9eb?sender=johlic)

#### **User Story**: _what does the user need – include some sort of WOW statement:_
- Users want the Checker to align with industry standard ([ACT](https://act-rules.github.io/pages/about/)) and to have fewer bugs and false positives

#### **Playback Demonstration**: _what will you be able to show at the end of the release / point release to demonstrate how you accomplished your user story. If possible, list what you target to demonstrate for each sprint:_
-   Review ACT mapping (rules to Success Criteria (checkpoints) against Checker's and see if Checker has conflicts - where Checker disagrees, and decide if Checker wants to do anything about it. Review recommendations with Subject Matter Experts (SME Connection)
- ACT published and proposed rule - gaps
- [ACT rule status sheet](https://docs.google.com/spreadsheets/d/1OSkPFocXk4K3zYLnwS78WLsWO4PvE5yRcsauyefuIUI/edit?pli=1#gid=0)
- Take discrepancies to SME Connection to decide what needs to have a Git issue

#### **Metric**: _how can Checker squad measure the impact of this change:_
-  
-
#### **Comms**: _when completed who should you communicate this change to, what will you tell them (concisely), and where?:_
- [ ] Slack poster
- [ ] Accessibility Update Call
- [ ] ACT Community

## Definition of Done

- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed
